<?php
/**
 * @date_of_create: 11/24/2021 AD 10:49
 */

namespace YiiMan\VirtualizorSdk\Responses\Admin;

/**
 * Class Plan
 * @package YiiMan\VirtualizorSdk\Responses\Admin
 * @property  integer $plid
 * @property  string  $plan_name
 * @property  string  $virt
 * @property  string  $ips
 * @property  string  $ips6
 * @property  string  $ips6_subnet
 * @property  string  $ips_int
 * @property  float   $space
 * @property  string  $inodes
 * @property  string  $ram
 * @property  string  $burst
 * @property  string  $swap
 * @property  string  $cpu
 * @property  string  $cores
 * @property  string  $cpu_percent
 * @property  string  $bandwidth
 * @property  string  $network_speed
 * @property  string  $upload_speed
 * @property  string  $nic_type
 * @property  string  $io
 * @property  string  $virtio
 * @property  string  $ubc
 * @property  string  $ploop
 * @property  string  $band_suspend
 * @property  string  $dns_nameserver
 * @property  string  $ppp
 * @property  string  $tuntap
 * @property  string  $control_panel
 * @property  string  $mgs
 * @property  string  $cpu_mode
 * @property  string  $sec_iso
 * @property  string  $hvm
 * @property  string  $kvm_cache
 * @property  string  $io_mode
 * @property  string  $osreinstall_limit
 * @property  string  $total_iops_sec
 * @property  string  $read_bytes_sec
 * @property  string  $write_bytes_sec
 * @property  string  $vnc_keymap
 * @property  string  $osid
 * @property  string  $kvm_vga
 * @property  string  $acceleration
 * @property  string  $vif_type
 * @property  string  $pv_on_hvm
 * @property  string  $iso
 * @property  string  $vnc
 * @property  string  $admin_managed
 * @property  string  $shadow
 * @property  string  $acpi
 * @property  string  $apic
 * @property  string  $pae
 * @property  string  $recipe
 * @property  string  $topology_sockets
 * @property  string  $topology_cores
 * @property  string  $topology_threads
 * @property  string  $disable_nw_config
 * @property  string  $rdp
 * @property  string  $openvz_features
 * @property  string  $speed_cap
 * @property  string  $numa
 * @property  string  $bpid
 * @property  string  $install_xentools
 * @property  string  $ippoolid
 * @property  string  $is_enabled
 * @property  string  $bus_driver
 * @property  string  $bus_driver_num
 * @property  string  $webuzo_data
 * @property  string  $fuse
 * @property  string  $ipip
 * @property  string  $ipgre
 * @property  string  $nfs
 * @property  string  $quotaugidlimit
 * @property  string  $iolimit
 * @property  string  $iopslimit
 */
class Plan extends \YiiMan\ApiStorm\Response\BaseResponse
{
    public $plid = 'int';
    public $plan_name = "";
    public $virt = '';
    public $ips = '';
    public $ips6 = '';
    public $ips6_subnet = '';
    public $ips_int = '';
    public $space = 'float';
    public $inodes = '';
    public $ram = '';
    public $burst = '';
    public $swap = '';
    public $cpu = '';
    public $cores = '';
    public $cpu_percent = '';
    public $bandwidth = '';
    public $network_speed = '';
    public $upload_speed = '';
    public $nic_type = '';
    public $io = '';
    public $virtio = '';
    public $ubc = '';
    public $ploop = '';
    public $band_suspend = '';
    public $dns_nameserver = '';
    public $ppp = '';
    public $tuntap = '';
    public $control_panel = '';
    public $mgs = '';
    public $cpu_mode = '';
    public $sec_iso = '';
    public $hvm = '';
    public $kvm_cache = '';
    public $io_mode = '';
    public $osreinstall_limit = '';
    public $total_iops_sec = '';
    public $read_bytes_sec = '';
    public $write_bytes_sec = '';
    public $vnc_keymap = '';
    public $osid = '';
    public $kvm_vga = '';
    public $acceleration = '';
    public $vif_type = '';
    public $pv_on_hvm = '';
    public $iso = '';
    public $vnc = '';
    public $admin_managed = '';
    public $shadow = '';
    public $acpi = '';
    public $apic = '';
    public $pae = '';
    public $recipe = '';
    public $topology_sockets = '';
    public $topology_cores = '';
    public $topology_threads = '';
    public $disable_nw_config = '';
    public $rdp = '';
    public $openvz_features = '';
    public $speed_cap = '';
    public $numa = '';
    public $bpid = '';
    public $install_xentools = '';
    public $ippoolid = '';
    public $is_enabled = '';
    public $bus_driver = '';
    public $bus_driver_num = '';
    public $webuzo_data = '';
    public $fuse = '';
    public $ipip = '';
    public $ipgre = '';
    public $nfs = '';
    public $quotaugidlimit = '';
    public $iolimit = '';
    public $iopslimit = '';
}